# Generated by Django 4.0.4 on 2022-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
                ('foto', models.ImageField(null=True, upload_to='juegos')),
                ('descripcion', models.TextField(null=True)),
                ('stock', models.PositiveSmallIntegerField(null=True)),
                ('garantia', models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 1')),
                ('imagen1', models.ImageField(null=True, upload_to='juegos')),
                ('imagen2', models.ImageField(null=True, upload_to='juegos')),
                ('imagen3', models.ImageField(null=True, upload_to='juegos')),
            ],
        ),
    ]
