# Generated by Django 4.0.4 on 2022-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
    ]
