# Generated by Django 4.1.3 on 2022-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_foto_alter_producto_imagen1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
                ('foto', models.ImageField(null=True, upload_to='Producto')),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='garantia',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Servicio'),
        ),
    ]
