# Generated by Django 4.1.3 on 2022-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicio_alter_producto_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('marca', models.TextField(null=True)),
                ('patente', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
    ]
