# Generated by Django 4.1.3 on 2022-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='numero',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hora',
            name='codigo',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
