# Generated by Django 4.1.3 on 2022-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hora_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='aceptada',
            field=models.BooleanField(null=True),
        ),
    ]
